name: Tests
on: [pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Run unit tests
        run: |
          go test -race -v . -count=1 -vet=off -timeout=30m
